package mfs.util.iso;

import org.jpos.iso.IFA_AMOUNT;
import org.jpos.iso.IFA_BINARY;
import org.jpos.iso.IFA_LLCHAR;
import org.jpos.iso.IFA_LLLCHAR;
import org.jpos.iso.IFA_LLNUM;
import org.jpos.iso.IFA_NUMERIC;
import org.jpos.iso.IFB_BITMAP;
import org.jpos.iso.IF_CHAR;
import org.jpos.iso.ISOBasePackager;
import org.jpos.iso.ISOFieldPackager;
import org.jpos.util.Logger;

public class FDMPackager extends ISOBasePackager {
	/* member class not found */
	// class FMD120Packager extends ISOBasePackager {
	//
	// protected ISOFieldPackager fld[];
	//
	// public FMD120Packager() {
	// fld = (new ISOFieldPackager[] { new IF_CHAR(30, "INVOICE NO."),// 0
	// new IF_CHAR(8, "AGENT ID"),// 1
	// new IF_CHAR(29, "AGENT BRANCH CD"),// 2*
	// new IF_CHAR(6, "PAYPER ID"),// 3*
	// new IF_CHAR(70, "REF1"),// 4*
	// new IF_CHAR(70, "REF2"),// 5*
	// new IF_CHAR(70, "REF3"),// 6*
	// new IF_CHAR(70, "REF4"),// 7*
	// new IFA_NUMERIC(2, "FUND TYPE"),// 8*
	// new IFA_NUMERIC(11, "VAT AMOUNT"),// 9*
	// new IFA_NUMERIC(2, "VAT RATE"),// 10*
	// new IFA_NUMERIC(11, "FEE AMOUNT CUSTOMER"),// 11*
	// new IFA_NUMERIC(11, "FEE VAT EXT. CUSTOMER"),// 12*
	// new IFA_NUMERIC(11, "FEE VAT AMOUNT CUSTOMER"),// 13*
	// new IFA_NUMERIC(11, "FEE AMOUNT BILLER"),// 14*
	// new IFA_NUMERIC(11, "FEE VAT EXT. BILLER"),// 15*
	// new IFA_NUMERIC(11, "FEE VAT AMOUNT BILLER"),// 16*
	// });
	// setFieldPackager(fld);
	//
	// }
	// }

	public FDMPackager() {
		// fdm120Packager = new FMD120Packager();
		fld = (new ISOFieldPackager[] {
				new IFA_NUMERIC(4, "MESSAGE TYPE INDICATOR"),// 0
				new IFB_BITMAP(64, "BIT MAP "),// 1
				new IFA_LLNUM(19, "PAN - PRIMARY ACCOUNT NUMBER"),// 2*
				new IFA_NUMERIC(6, "PROCESSING CODE"),// 3*
				new IFA_NUMERIC(12, "AMOUNT, TRANSACTION"),// 4*
				new IFA_NUMERIC(12, "AMOUNT, SETTLEMENT"),// 5
				new IFA_NUMERIC(12, "AMOUNT, CARDHOLDER BILLING"),// 6
				new IFA_NUMERIC(10, "TRANSMISSION DATE AND TIME"),// 7*
				new IFA_NUMERIC(8, "AMOUNT, CARDHOLDER BILLING FEE"),// 8
				new IFA_NUMERIC(8, "CONVERSION RATE, SETTLEMENT"),// 9
				new IFA_NUMERIC(8, "CONVERSION RATE, CARDHOLDER BILLING"),// 10
				new IFA_NUMERIC(6, "SYSTEM TRACE AUDIT NUMBER"),// 11*
				new IFA_NUMERIC(6, "TIME, LOCAL TRANSACTION"),// 12*
				new IFA_NUMERIC(4, "DATE, LOCAL TRANSACTION"),// 13*
				new IFA_NUMERIC(4, "DATE, EXPIRATION"),// 14
				new IFA_NUMERIC(4, "DATE, SETTLEMENT"),// 15
				new IFA_NUMERIC(4, "DATE, CONVERSION"),// 16
				new IFA_NUMERIC(4, "DATE, CAPTURE"),// 17
				new IFA_NUMERIC(4, "MERCHANTS TYPE"), // 18*
				new IFA_NUMERIC(3, "ACQUIRING INSTITUTION COUNTRY CODE"),// 19
				new IFA_NUMERIC(3, "PAN EXTENDED COUNTRY CODE"),// 20
				new IFA_NUMERIC(3, "FORWARDING INSTITUTION COUNTRY CODE"), // 21
				new IFA_NUMERIC(3, "POINT OF SERVICE ENTRY MODE"),// 22*
				new IFA_NUMERIC(3, "CARD SEQUENCE NUMBER"),// 23
				new IFA_NUMERIC(3, "NETWORK INTERNATIONAL IDENTIFIEER"), // 24
				new IFA_NUMERIC(2, "POINT OF SERVICE CONDITION CODE"), // 25
				new IFA_NUMERIC(2, "POINT OF SERVICE PIN CAPTURE CODE"), // 26
				new IFA_NUMERIC(1, "AUTHORIZATION IDENTIFICATION RESP LEN"), // 27
				new IFA_AMOUNT(9, "AMOUNT, TRANSACTION FEE"),// 28
				new IFA_AMOUNT(9, "AMOUNT, SETTLEMENT FEE"),// 29
				new IFA_AMOUNT(9, "AMOUNT, TRANSACTION PROCESSING FEE"),// 30
				new IFA_AMOUNT(9, "AMOUNT, SETTLEMENT PROCESSING FEE"),// 31
				new IFA_LLNUM(11, "ACQUIRING INSTITUTION IDENT CODE"),// 32*
				new IFA_LLNUM(11, "FORWARDING INSTITUTION IDENT CODE"),// 33
				new IFA_LLCHAR(28, "PAN EXTENDED"),// 34
				new IFA_LLNUM(37, "TRACK 2 DATA"),// 35
				new IFA_LLLCHAR(104, "TRACK 3 DATA"), // 36
				new IF_CHAR(12, "RETRIEVAL REFERENCE NUMBER"),// 37*
				new IF_CHAR(6, "AUTHORIZATION IDENTIFICATION RESPONSE"), // 38*
				new IF_CHAR(2, "RESPONSE CODE"), // 39*
				new IF_CHAR(3, "SERVICE RESTRICTION CODE"),// 40
				new IF_CHAR(16, "CARD ACCEPTOR TERMINAL IDENTIFICACION"),// 41*
																			// length
																			// fdm
																			// =
																			// 16
				new IF_CHAR(15, "CARD ACCEPTOR IDENTIFICATION CODE"),// 42*
				new IF_CHAR(40, "CARD ACCEPTOR NAME/LOCATION"),// 43*
				new IFA_LLCHAR(25, "ADITIONAL RESPONSE DATA"),// 44
				new IFA_LLCHAR(76, "TRACK 1 DATA"),// 45
				new IFA_LLLCHAR(999, "ADITIONAL DATA - ISO"),// 46
				new IFA_LLLCHAR(999, "ADITIONAL DATA - NATIONAL"),// 47
				new IFA_LLLCHAR(999, "ADITIONAL DATA - PRIVATE"),// 48
				// new ISOMsgFieldPackager(new IFA_LLLBINARY(999,
				// "EUROPAY FIELD 48"), fdm120Packager), // 48
				new IF_CHAR(3, "CURRENCY CODE, TRANSACTION"),// 49*
				new IF_CHAR(3, "CURRENCY CODE, SETTLEMENT"),// 50
				new IF_CHAR(3, "CURRENCY CODE, CARDHOLDER BILLING"),// 51
				new IFA_BINARY(8, "PIN DATA"),// 52*
				new IFA_NUMERIC(16, "SECURITY RELATED CONTROL INFORMATION"),// 53
				new IFA_LLLCHAR(120, "ADDITIONAL AMOUNTS"),// 54
				new IFA_LLLCHAR(999, "RESERVED ISO"),// 55
				new IFA_LLLCHAR(999, "RESERVED ISO"),// 56
				new IFA_LLLCHAR(999, "RESERVED NATIONAL"),// 57
				new IFA_LLLCHAR(999, "RESERVED NATIONAL"),// 58
				new IFA_LLLCHAR(999, "RESERVED NATIONAL"),// 59
				new IFA_LLLCHAR(999, "RESERVED PRIVATE"),// 60
				new IFA_LLLCHAR(999, "RESERVED PRIVATE"),// 61
				new IFA_LLLCHAR(999, "RESERVED PRIVATE"),// 62
				new IFA_LLLCHAR(999, "RESERVED PRIVATE"),// 63
				new IFA_BINARY(8, "MESSAGE AUTHENTICATION CODE FIELD"),// 64
				new IFA_BINARY(8, "BITMAP, EXTENDED"),// 65
				new IFA_NUMERIC(1, "SETTLEMENT CODE"),// 66
				new IFA_NUMERIC(2, "EXTENDED PAYMENT CODE"),// 67
				new IFA_NUMERIC(3, "RECEIVING INSTITUTION COUNTRY CODE"),// 68
				new IFA_NUMERIC(3, "SETTLEMENT INSTITUTION COUNTRY CODE"),// 69
				new IFA_NUMERIC(3, "NETWORK MANAGEMENT INFORMATION CODE"),// 70
				new IFA_NUMERIC(4, "MESSAGE NUMBER"),// 71
				new IFA_NUMERIC(4, "MESSAGE NUMBER LAST"),// 72
				new IFA_NUMERIC(6, "DATE ACTION"),// 73
				new IFA_NUMERIC(10, "CREDITS NUMBER"),// 74
				new IFA_NUMERIC(10, "CREDITS REVERSAL NUMBER"),// 75
				new IFA_NUMERIC(10, "DEBITS NUMBER"),// 76
				new IFA_NUMERIC(10, "DEBITS REVERSAL NUMBER"),// 77
				new IFA_NUMERIC(10, "TRANSFER NUMBER"),// 78
				new IFA_NUMERIC(10, "TRANSFER REVERSAL NUMBER"),// 79
				new IFA_NUMERIC(10, "INQUIRIES NUMBER"),// 80
				new IFA_NUMERIC(10, "AUTHORIZATION NUMBER"),// 81
				new IFA_NUMERIC(12, "CREDITS, PROCESSING FEE AMOUNT"),// 82
				new IFA_NUMERIC(12, "CREDITS, TRANSACTION FEE AMOUNT"),// 83
				new IFA_NUMERIC(12, "DEBITS, PROCESSING FEE AMOUNT"),// 84
				new IFA_NUMERIC(12, "DEBITS, TRANSACTION FEE AMOUNT"),// 85
				new IFA_NUMERIC(16, "CREDITS, AMOUNT"),// 86
				new IFA_NUMERIC(16, "CREDITS, REVERSAL AMOUNT"),// 87
				new IFA_NUMERIC(16, "DEBITS, AMOUNT"),// 88
				new IFA_NUMERIC(16, "DEBITS, REVERSAL AMOUNT"),// 89
				new IFA_NUMERIC(42, "ORIGINAL DATA ELEMENTS"),// 90
				new IF_CHAR(1, "FILE UPDATE CODE"),// 91
				new IF_CHAR(2, "FILE SECURITY CODE"),// 92
				new IF_CHAR(5, "RESPONSE INDICATOR"),// 93
				new IF_CHAR(7, "SERVICE INDICATOR"),// 94
				new IF_CHAR(42, "REPLACEMENT AMOUNTS"),// 95
				new IFA_BINARY(8, "MESSAGE SECURITY CODE"),// 96
				new IFA_AMOUNT(17, "AMOUNT, NET SETTLEMENT"),// 97
				new IF_CHAR(25, "PAYEE"),// 98
				new IFA_LLNUM(11, "SETTLEMENT INSTITUTION IDENT CODE"),// 99
				new IFA_LLNUM(11, "RECEIVING INSTITUTION IDENT CODE"),// 100*
				new IFA_LLCHAR(17, "FILE NAME"),// 101
				new IFA_LLCHAR(28, "ACCOUNT IDENTIFICATION 1"),// 102
				new IFA_LLCHAR(28, "ACCOUNT IDENTIFICATION 2"),// 103
				new IFA_LLLCHAR(100, "TRANSACTION DESCRIPTION"),// 104
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 105
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 106
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 107
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 108
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 119
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 110
				new IFA_LLLCHAR(999, "RESERVED ISO USE"),// 111
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 112
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 113
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 114
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 115
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 116
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 117
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 118
				new IFA_LLLCHAR(999, "RESERVED NATIONAL USE"),// 119

				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 120 **
				// new ISOMsgFieldPackager(new IFA_LLLCHAR(999,
				// "RESERVED PRIVATE USE"), fdm120Packager),// 120 **

				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 121
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 122
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 123
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 124
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 125
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 126
				new IFA_LLLCHAR(999, "RESERVED PRIVATE USE"),// 127
				new IFA_LLLCHAR(999, "MAC 2") });// 128
		setFieldPackager(fld);
	}

	public void setLogger(Logger logger, String realm) {
		this.logger = logger;
		this.realm = realm;
		// fdm120Packager.setLogger(logger, (new StringBuilder()).append(realm)
		// .append(".field-120").toString());
	}

	// protected ISOPackager fdm120Packager;
	protected ISOFieldPackager fld[];
}